/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MyCard {
    }
    interface MyCardGroup {
    }
    interface MyContainer {
    }
}
declare global {
    interface HTMLMyCardElement extends Components.MyCard, HTMLStencilElement {
    }
    var HTMLMyCardElement: {
        prototype: HTMLMyCardElement;
        new (): HTMLMyCardElement;
    };
    interface HTMLMyCardGroupElement extends Components.MyCardGroup, HTMLStencilElement {
    }
    var HTMLMyCardGroupElement: {
        prototype: HTMLMyCardGroupElement;
        new (): HTMLMyCardGroupElement;
    };
    interface HTMLMyContainerElement extends Components.MyContainer, HTMLStencilElement {
    }
    var HTMLMyContainerElement: {
        prototype: HTMLMyContainerElement;
        new (): HTMLMyContainerElement;
    };
    interface HTMLElementTagNameMap {
        "my-card": HTMLMyCardElement;
        "my-card-group": HTMLMyCardGroupElement;
        "my-container": HTMLMyContainerElement;
    }
}
declare namespace LocalJSX {
    interface MyCard {
    }
    interface MyCardGroup {
    }
    interface MyContainer {
    }
    interface IntrinsicElements {
        "my-card": MyCard;
        "my-card-group": MyCardGroup;
        "my-container": MyContainer;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "my-card": LocalJSX.MyCard & JSXBase.HTMLAttributes<HTMLMyCardElement>;
            "my-card-group": LocalJSX.MyCardGroup & JSXBase.HTMLAttributes<HTMLMyCardGroupElement>;
            "my-container": LocalJSX.MyContainer & JSXBase.HTMLAttributes<HTMLMyContainerElement>;
        }
    }
}
